---
title: Peter Hironaka
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  sf:
    title: SF
    output: true
  uploads:
    title: Uploads
    output: true
  la:
    title: city-la
    output: true
    photo: IMG_5229.jpg
email: your-email@domain.com
description: Nike West Event Recaps.
baseurl: 
url: http://yourdomain.com
twitter_username: peterhironaka
github_username: phironaka
markdown: kramdown
permalink: pretty
